<!DOCTYPE html>
<html lang="EN" xmlns:form="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">



    <title>Coffee shop</title>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col xxl-5">
            <div class="goods_box" id="goods">
                <div class="menu">
                     <input type="text" placeholder="Search" class="search">
                     <button class="add btn-success" data-bs-toggle="model" data-bs-target="#exampleMpdal">&#10010;</button>
                </div>



            </div>
        </div>
        <div class="col-xs-12 col xxl-7"></div>
    </div>
</div>






<body>
<script src="/js/bootstrap.bundle.min.js"></script>
<script src="/js/sweetalert2.all.min.js"></script>
<script src="/js/list.min.js"></script>
<script src="/js/main.js"></script>








<h1>Coffee Shop</h1>

<h2>Home Page</h2>

    <h4> <-- <a href="/"> Back </a> </h4>

</body>



</html>